services:
  - type: web
    name: e-learn
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        headers:
          - key: X-Frame-Options
            value: DENY
          - key: X-XSS-Protection
            value: 1; mode=block
          - key: X-Content-Type-Options
            value: nosniff
      - path: /*.js
        headers:
          - key: Content-Type
            value: application/javascript
      - path: /*.mjs
        headers:
          - key: Content-Type
            value: application/javascript
      - path: /*.css
        headers:
          - key: Content-Type
            value: text/css
