services:
  - type: web
    name: e-learn
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        headers:
          - key: X-Frame-Options
            value: DENY
          - key: X-XSS-Protection
            value: "1; mode=block"
          - key: X-Content-Type-Options
            value: nosniff
          - key: Referrer-Policy
            value: strict-origin-when-cross-origin
      - path: /*.js
        headers:
          - key: Content-Type
            value: application/javascript
          - key: Cache-Control
            value: public, max-age=31536000, immutable
      - path: /*.mjs
        headers:
          - key: Content-Type
            value: application/javascript
          - key: Cache-Control
            value: public, max-age=31536000, immutable
      - path: /*.css
        headers:
          - key: Content-Type
            value: text/css
          - key: Cache-Control
            value: public, max-age=31536000, immutable
      - path: /*.html
        headers:
          - key: Content-Type
            value: text/html; charset=utf-8
          - key: Cache-Control
            value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
